Introduction &   CREATION OF DATAFRAMSES

In [1]:
import numpy as np
import pandas as pd

1 -: Using dict

In [2]:
data = {
    "name" : ["a" , "b"  ,"c"],
    "age" : [12,12,13],
    "city" : ["Mumbai" , "Kolokata" , "Delhi"]
}

df = pd.DataFrame(data)
df

  name  age      city
0    a   12    Mumbai
1    b   12  Kolokata
2    c   13     Delhi

2 -: Using list of list

In [3]:
data = [
     ["a" , "b"  ,"c"],
     [12,12,13],
    ["Mumbai" , "Kolokata" , "Delhi"]
]

df = pd.DataFrame(data , columns=["Name" , "Age" ,"City"])
df

     Name       Age   City
0       a         b      c
1      12        12     13
2  Mumbai  Kolokata  Delhi

3 -: From Numpy array

In [4]:
arr = np.array([
    ["Amit" , 23 , "Mumbai"],
    ["Rahul " , 22 , "Hyd"],
    ["Ketan" , 30 , "Delhi"]
])

name=pd.Series(["Amit" , "Rahul" , "Ketan"])
age=pd.Series([23,22,30])
city=pd.Series(["Mumbai" , "Hyd" , "Delhi"])

df = pd.DataFrame({ "Name":name , "Age":age , "City":city})
df

    Name  Age    City
0   Amit   23  Mumbai
1  Rahul   22     Hyd
2  Ketan   30   Delhi

4 -: CSV / EXCEL FILE

In [5]:
#CSV
df = pd.read_csv("dummy_data_csv.csv")
df

    Name  Age       City  Marks
0  Alice   20      Delhi     85
1    Bob   19     Mumbai     78
2  Kelly   21       Pune     92
3   John   22     Jaipur     88
4   Emma   20  Bangalore     95
5  David   23  Hyderabad     81

In [6]:
#tsv
df = pd.read_csv("dummy_data_tsv.tsv", sep ="\t")
df

    Name  Age       City  Marks
0  Alice   20      Delhi     85
1    Bob   19     Mumbai     78
2  Kelly   21       Pune     92
3   John   22     Jaipur     88
4   Emma   20  Bangalore     95
5  David   23  Hyderabad     81

Excel

In [7]:
import pandas as pd

# TSV file read karo
df = pd.read_csv("dummy_data_tsv.tsv", sep="\t")

# Excel file banao
df.to_excel("dummy_data_excel.xlsx", index=False)

print("Excel file created successfully!")

Excel file created successfully!

In [8]:
!pip install openpyxl

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: openpyxl in c:\programdata\anaconda3\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\programdata\anaconda3\lib\site-packages (from openpyxl) (2.0.0)

In [9]:
#pip install openpyxl
df = pd.read_excel("dummy_data_excel.xlsx")
df

    Name  Age       City  Marks
0  Alice   20      Delhi     85
1    Bob   19     Mumbai     78
2  Kelly   21       Pune     92
3   John   22     Jaipur     88
4   Emma   20  Bangalore     95
5  David   23  Hyderabad     81

4 -: From URL

In [ ]:
# CSV
import pandas as pd
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv"
df = pd.read_csv(url)
df.head()

In [ ]:
# JSON
import pandas as pd
url = "https://jsonplaceholder.typicode.com/users"
df = pd.read_json(url)
df.head()

,id,name,username,email,address,phone,website,company
0,1,Leanne Graham,Bret,Sincere@april.biz,"{'street': 'Kulas Light', 'suite': 'Apt. 556',...",1-770-736-8031 x56442,hildegard.org,"{'name': 'Romaguera-Crona', 'catchPhrase': 'Mu..."
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,"{'street': 'Victor Plains', 'suite': 'Suite 87...",010-692-6593 x09125,anastasia.net,"{'name': 'Deckow-Crist', 'catchPhrase': 'Proac..."
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,"{'street': 'Douglas Extension', 'suite': 'Suit...",1-463-123-4447,ramiro.info,"{'name': 'Romaguera-Jacobson', 'catchPhrase': ..."
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,"{'street': 'Hoeger Mall', 'suite': 'Apt. 692',...",493-170-9623 x156,kale.biz,"{'name': 'Robel-Corkery', 'catchPhrase': 'Mult..."
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,"{'street': 'Skiles Walks', 'suite': 'Suite 351...",(254)954-1289,demarco.info,"{'name': 'Keebler LLC', 'catchPhrase': 'User-c..."

In [ ]:
#HTMl
! pip install lxml

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: lxml in c:\programdata\anaconda3\lib\site-packages (5.3.0)

In [ ]:
import lxml
print("OK")

OK

In [ ]:
# HTML Table
url = "https://en.wikipedia.org/wiki/Indian_Institutes_of_Information_Technology"
table = pd.read_html(url)
len(table)

In [2]:
data = {
    "name" : ["a" , "b"  ,"c"],
    "age" : [12,12,13],
    "city" : ["Mumbai" , "Kolokata" , "Delhi"]
}

df = pd.DataFrame(data)
df

  name  age      city
0    a   12    Mumbai
1    b   12  Kolokata
2    c   13     Delhi

In [ ]:
df["age"]+df["age"] # ndarray concept

0    24
1    24
2    26
Name: age, dtype: int64