In [1]:
import pandas as pd
import numpy as np

In [3]:
pd.__version__

'2.3.3'

In [4]:
#series
pd.Series([10,20,30] , index = ["a","b","c"])

a    10
b    20
c    30
dtype: int64

In [8]:
#DataFrame
data ={
    "name":["a","b","c"],
    "age": [11,12,12]
}
df = pd.DataFrame(data)
df


# each row in dataframe are series

  name  age
0    a   11
1    b   12
2    c   12

In [11]:
#head = top 5 rowa
# tail = bottom 5 rows
df.head(1)
df.tail()

  name  age
0    a   11
1    b   12
2    c   12

In [ ]:
#Shape 
df.shape

(3, 2)

In [14]:
# len
len(df)

3

DataFrame Dtypes

In [15]:
df.dtypes

name    object
age      int64
dtype: object

In [19]:
# age is using 64 bit but max max to age will be 100,110 so we can try to  reduce the size
df["age"] = df["age"].astype("int16")
df.dtypes

name    object
age      int16
dtype: object

index , columns and labels in dataframe

In [20]:
#Columns attribute property
df.columns

Index(['name', 'age'], dtype='object')

In [21]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [22]:
from numpy.random import randint as ri
a = ri(1,100,20).reshape(5,4)
a

array([[71, 63, 18, 75],
       [75, 96, 32, 72],
       [16,  9,  6, 70],
       [38, 44, 91, 12],
       [23, 77, 54, 32]], dtype=int32)

In [57]:
r = ["A", "B" ,"C" ,"D" ,"E"]
c = ["W", "X" ,"Y", "Z"]
df=pd.DataFrame(data = a , index = r , columns = c)
df

    W   X   Y   Z
A  71  63  18  75
B  75  96  32  72
C  16   9   6  70
D  38  44  91  12
E  23  77  54  32

In [40]:
df.shape

(5, 4)

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, A to E
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   W       5 non-null      int32
 1   X       5 non-null      int32
 2   Y       5 non-null      int32
 3   Z       5 non-null      int32
dtypes: int32(4)
memory usage: 120.0+ bytes

In [42]:
df.describe()

               W          X          Y          Z
count   5.000000   5.000000   5.000000   5.000000
mean   44.600000  57.800000  40.200000  52.200000
std    27.153269  33.267101  33.544001  28.516662
min    16.000000   9.000000   6.000000  12.000000
25%    23.000000  44.000000  18.000000  32.000000
50%    38.000000  63.000000  32.000000  70.000000
75%    71.000000  77.000000  54.000000  72.000000
max    75.000000  96.000000  91.000000  75.000000

In [43]:
df.columns

Index(['W', 'X', 'Y', 'Z'], dtype='object')

In [44]:
df.index

Index(['A', 'B', 'C', 'D', 'E'], dtype='object')

In [ ]:
df['X']  # dtype = series

A    63
B    96
C     9
D    44
E    77
Name: X, dtype: int32

In [46]:
df[["X","Y"]]

    X   Y
A  63  18
B  96  32
C   9   6
D  44  91
E  77  54

DF.Drop

In [47]:
df

    W   X   Y   Z
A  71  63  18  75
B  75  96  32  72
C  16   9   6  70
D  38  44  91  12
E  23  77  54  32

In [48]:
df.drop("D")

    W   X   Y   Z
A  71  63  18  75
B  75  96  32  72
C  16   9   6  70
E  23  77  54  32

In [49]:
df

    W   X   Y   Z
A  71  63  18  75
B  75  96  32  72
C  16   9   6  70
D  38  44  91  12
E  23  77  54  32

In [50]:
df.drop(["A","B"])

    W   X   Y   Z
C  16   9   6  70
D  38  44  91  12
E  23  77  54  32

In [51]:
df

    W   X   Y   Z
A  71  63  18  75
B  75  96  32  72
C  16   9   6  70
D  38  44  91  12
E  23  77  54  32

In [53]:
df.drop("X", axis=1)

    W   Y   Z
A  71  18  75
B  75  32  72
C  16   6  70
D  38  91  12
E  23  54  32

In [54]:
df

    W   X   Y   Z
A  71  63  18  75
B  75  96  32  72
C  16   9   6  70
D  38  44  91  12
E  23  77  54  32

In [ ]:
df.drop("E", inplace=True) # drop not return anything just do change in irginal when inplace = True

In [ ]:
df # change orginal table

    W   X   Y   Z
A  71  63  18  75
B  75  96  32  72
C  16   9   6  70
D  38  44  91  12

Selecting / Indexing Rows

In [58]:
df

    W   X   Y   Z
A  71  63  18  75
B  75  96  32  72
C  16   9   6  70
D  38  44  91  12
E  23  77  54  32

In [62]:
# selecting row with label :- C or index 3 --> Subsetting
print(df .loc["C"])
print("="*100)
df.iloc[2]

W    16
X     9
Y     6
Z    70
Name: C, dtype: int32
====================================================================================================

W    16
X     9
Y     6
Z    70
Name: C, dtype: int32

In [66]:
#Selecting Multiple Row with label - "A" and "C"==> SubSetting
print(df.loc[["A","C"]])
print("="*100)
df.iloc[[0,1]]

    W   X   Y   Z
A  71  63  18  75
C  16   9   6  70
====================================================================================================

    W   X   Y   Z
A  71  63  18  75
B  75  96  32  72

Slicing for multiple rowa -- first 3 row ==> slicing

In [69]:
print(df.loc["A":"E"])
print("="*100)
print(df.iloc[0:5])

    W   X   Y   Z
A  71  63  18  75
B  75  96  32  72
C  16   9   6  70
D  38  44  91  12
E  23  77  54  32
====================================================================================================
    W   X   Y   Z
A  71  63  18  75
B  75  96  32  72
C  16   9   6  70
D  38  44  91  12
E  23  77  54  32

Subsetting DataFrame

In [70]:
df

    W   X   Y   Z
A  71  63  18  75
B  75  96  32  72
C  16   9   6  70
D  38  44  91  12
E  23  77  54  32

In [73]:
# element at row "B" and Col ="Y"
print(df.loc["B","Y"])
print("="*100)
print(df.iloc[1,2])

32
====================================================================================================
32

In [77]:
#Subset comprising of row B and D , and Columns W and Y
print(df.loc[["B","D"],["W","Y"]])
print("="*100)
print(df.iloc[[1,3],[0,2]])

    W   Y
B  75  32
D  38  91
====================================================================================================
    W   Y
B  75  32
D  38  91

In [78]:
df

    W   X   Y   Z
A  71  63  18  75
B  75  96  32  72
C  16   9   6  70
D  38  44  91  12
E  23  77  54  32

Subsetting data frame bases on some condition for cell

In [79]:
# condition where value>40
df>40

       W      X      Y      Z
A   True   True  False   True
B   True   True  False   True
C  False  False  False   True
D  False   True   True  False
E  False   True   True  False

In [80]:
print(df>40)

       W      X      Y      Z
A   True   True  False   True
B   True   True  False   True
C  False  False  False   True
D  False   True   True  False
E  False   True   True  False

In [81]:
booldf = df>40
df[booldf]

      W     X     Y     Z
A  71.0  63.0   NaN  75.0
B  75.0  96.0   NaN  72.0
C   NaN   NaN   NaN  70.0
D   NaN  44.0  91.0   NaN
E   NaN  77.0  54.0   NaN

In [82]:
df

    W   X   Y   Z
A  71  63  18  75
B  75  96  32  72
C  16   9   6  70
D  38  44  91  12
E  23  77  54  32

In [83]:
df>40

       W      X      Y      Z
A   True   True  False   True
B   True   True  False   True
C  False  False  False   True
D  False   True   True  False
E  False   True   True  False

In [84]:
df[df>40]

      W     X     Y     Z
A  71.0  63.0   NaN  75.0
B  75.0  96.0   NaN  72.0
C   NaN   NaN   NaN  70.0
D   NaN  44.0  91.0   NaN
E   NaN  77.0  54.0   NaN

Subsettting  data frames bases on some condition for a some row

In [90]:
matrix_data= np.matrix("21,182,73;24,175,66;17,168,59;21,192,93;,24,185,86")
matrix_data

matrix([[ 21, 182,  73],
        [ 24, 175,  66],
        [ 17, 168,  59],
        [ 21, 192,  93],
        [ 24, 185,  86]])

In [91]:
r = ["A","B","C","D","E"]
c= ["Age","Height","Weight"]
df = pd.DataFrame(data = matrix_data, index = r , columns=c)
df

   Age  Height  Weight
A   21     182      73
B   24     175      66
C   17     168      59
D   21     192      93
E   24     185      86

In [95]:
print("\nRow with Height >180cm", "-"*35, sep ="")
df[df["Height"]>180]

Row with Height >180cm-----------------------------------

   Age  Height  Weight
A   21     182      73
D   21     192      93
E   24     185      86

In [98]:
print("\nRows with height >180 and weight >80  ", "-"*30 , sep="")
df[(df["Height"]>180) & (df["Weight"]>80)]

Rows with height >180 and weight >80  ------------------------------

   Age  Height  Weight
D   21     192      93
E   24     185      86

Resettng the index of your dataframe

In [99]:
df

   Age  Height  Weight
A   21     182      73
B   24     175      66
C   17     168      59
D   21     192      93
E   24     185      86

In [100]:
df.index

Index(['A', 'B', 'C', 'D', 'E'], dtype='object')

In [102]:
df.reset_index()

  index  Age  Height  Weight
0     A   21     182      73
1     B   24     175      66
2     C   17     168      59
3     D   21     192      93
4     E   24     185      86

In [103]:
df.reset_index(drop =True)

   Age  Height  Weight
0   21     182      73
1   24     175      66
2   17     168      59
3   21     192      93
4   24     185      86

Inset new row

In [105]:
df.loc["F"]=[22,160,56]
df

   Age  Height  Weight
A   21     182      73
B   24     175      66
C   17     168      59
D   21     192      93
E   24     185      86
F   22     160      56

In [106]:
df

   Age  Height  Weight
A   21     182      73
B   24     175      66
C   17     168      59
D   21     192      93
E   24     185      86
F   22     160      56

Insert new column

In [110]:
df["BMI"]=df["Weight"]/(df["Height"]/100)**2
df

   Age  Height  Weight        BMI
A   21     182      73  22.038401
B   24     175      66  21.551020
C   17     168      59  20.904195
D   21     192      93  25.227865
E   24     185      86  25.127831
F   22     160      56  21.875000

In [112]:
df["Profession"]= "Student Teacher Engineer Doctor Nurse Student".split()
df

   Age  Height  Weight        BMI Profession
A   21     182      73  22.038401    Student
B   24     175      66  21.551020    Teacher
C   17     168      59  20.904195   Engineer
D   21     192      93  25.227865     Doctor
E   24     185      86  25.127831      Nurse
F   22     160      56  21.875000    Student

Rename The index of DataFrame

In [113]:
df.set_index("Profession")

            Age  Height  Weight        BMI
Profession
Student      21     182      73  22.038401
Teacher      24     175      66  21.551020
Engineer     17     168      59  20.904195
Doctor       21     192      93  25.227865
Nurse        24     185      86  25.127831
Student      22     160      56  21.875000

In [114]:
df

   Age  Height  Weight        BMI Profession
A   21     182      73  22.038401    Student
B   24     175      66  21.551020    Teacher
C   17     168      59  20.904195   Engineer
D   21     192      93  25.227865     Doctor
E   24     185      86  25.127831      Nurse
F   22     160      56  21.875000    Student

In [116]:
df.index=["L","U","C","K","Y","Y"]
df

   Age  Height  Weight        BMI Profession
L   21     182      73  22.038401    Student
U   24     175      66  21.551020    Teacher
C   17     168      59  20.904195   Engineer
K   21     192      93  25.227865     Doctor
Y   24     185      86  25.127831      Nurse
Y   22     160      56  21.875000    Student

Rename Columns

In [118]:
df.columns=["a","h","w","b","p"]
df

    a    h   w          b         p
L  21  182  73  22.038401   Student
U  24  175  66  21.551020   Teacher
C  17  168  59  20.904195  Engineer
K  21  192  93  25.227865    Doctor
Y  24  185  86  25.127831     Nurse
Y  22  160  56  21.875000   Student