PAndas 4 --: Advacnced Operations on DataFrame

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.DataFrame(
    {
        "A" : [1,2,np.nan],
        "B" : [5,np.nan,np.nan],
        "C" : [1,2,3]
    }
)
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       2 non-null      float64
 1   B       1 non-null      float64
 2   C       3 non-null      int64
dtypes: float64(2), int64(1)
memory usage: 204.0 bytes

In [5]:
df["Country"]="IND US UK".split()

In [6]:
df

     A    B  C Country
0  1.0  5.0  1     IND
1  2.0  NaN  2      US
2  NaN  NaN  3      UK

In [7]:
#"Make country as new index"
df.set_index("Country" , inplace = True)

In [8]:
df

           A    B  C
Country
IND      1.0  5.0  1
US       2.0  NaN  2
UK       NaN  NaN  3

In [11]:
df.iloc[1,1]

np.float64(nan)

In [13]:
df.isna()

             A      B      C
Country
IND      False  False  False
US       False   True  False
UK        True   True  False

In [14]:
df.notna()

             A      B     C
Country
IND       True   True  True
US        True  False  True
UK       False  False  True

Handling NaN Values

In [15]:
# DROP ANY ROW WITH A NaN values
df

           A    B  C
Country
IND      1.0  5.0  1
US       2.0  NaN  2
UK       NaN  NaN  3

In [18]:
df.dropna()

           A    B  C
Country
IND      1.0  5.0  1

In [19]:
# DROP ANY column wuth a NaN values
df

           A    B  C
Country
IND      1.0  5.0  1
US       2.0  NaN  2
UK       NaN  NaN  3

In [20]:
df.dropna(axis=1)

         C
Country
IND      1
US       2
UK       3

In [ ]:
#Drooping a row with a minimun 2 NaN values using "thresh" parameter
df

           A    B  C
Country
IND      1.0  5.0  1
US       2.0  NaN  2
UK       NaN  NaN  3

In [22]:
df.dropna(thresh=2)

           A    B  C
Country
IND      1.0  5.0  1
US       2.0  NaN  2

In [23]:
#Drooping a column with a minimun 2 NaN values using "thresh" parameter
df

           A    B  C
Country
IND      1.0  5.0  1
US       2.0  NaN  2
UK       NaN  NaN  3

In [24]:
df.dropna(axis=1, thresh =2)

           A  C
Country
IND      1.0  1
US       2.0  2
UK       NaN  3

In [25]:
# Filling values with a computed value ( mean of column A)
df

           A    B  C
Country
IND      1.0  5.0  1
US       2.0  NaN  2
UK       NaN  NaN  3

In [27]:
df.fillna(value=df["A"].mean())

           A    B  C
Country
IND      1.0  5.0  1
US       2.0  1.5  2
UK       1.5  1.5  3

In [29]:
#Reset Index
df.reset_index(inplace =True)

In [30]:
df

  Country    A    B  C
0     IND  1.0  5.0  1
1      US  2.0  NaN  2
2      UK  NaN  NaN  3

Categorical Operation

In [31]:
df

  Country    A    B  C
0     IND  1.0  5.0  1
1      US  2.0  NaN  2
2      UK  NaN  NaN  3

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Country  3 non-null      object
 1   A        2 non-null      float64
 2   B        1 non-null      float64
 3   C        3 non-null      int64
dtypes: float64(2), int64(1), object(1)
memory usage: 228.0+ bytes

In [34]:
# convert counrty as categorical column
df["Country"]=df["Country"].astype("category")
df

  Country    A    B  C
0     IND  1.0  5.0  1
1      US  2.0  NaN  2
2      UK  NaN  NaN  3

In [ ]:
df.info() # type of country is change to object to category

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Country  3 non-null      category
 1   A        2 non-null      float64
 2   B        1 non-null      float64
 3   C        3 non-null      int64
dtypes: category(1), float64(2), int64(1)
memory usage: 339.0 bytes

In [36]:
df["Country"].cat.categories

Index(['IND', 'UK', 'US'], dtype='object')

In [37]:
df["Country"].cat.codes

0    0
1    2
2    1
dtype: int8

Memory Optimization

In [ ]:
#changes C ( int64 to int32)
df["C"]=df["C"].astype("int32")
df

  Country    A    B  C
0     IND  1.0  5.0  1
1      US  2.0  NaN  2
2      UK  NaN  NaN  3

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Country  3 non-null      category
 1   A        2 non-null      float64
 2   B        1 non-null      float64
 3   C        3 non-null      int32
dtypes: category(1), float64(2), int32(1)
memory usage: 327.0 bytes

GroupBy & Mean

In [42]:
data = {
    "Company":["GOOGLE","GOOGLE","MICROSOFT","MICROSOFT","FACEBOOK","FACEBOOK"],
    "Person":["Akshay","Ankit","Sahil","Dharmesh","Sunil","Manish"],
    "Sales":[200,120,340,124,243,350]
    
}
df = pd.DataFrame(data)
df

     Company    Person  Sales
0     GOOGLE    Akshay    200
1     GOOGLE     Ankit    120
2  MICROSOFT     Sahil    340
3  MICROSOFT  Dharmesh    124
4   FACEBOOK     Sunil    243
5   FACEBOOK    Manish    350

In [48]:
# Grouping by"Company" column and listing means sales
df.groupby("Company").Sales.mean()

Company
FACEBOOK     296.5
GOOGLE       160.0
MICROSOFT    232.0
Name: Sales, dtype: float64

In [49]:
# total sales
df.groupby("Company").Sales.sum()

Company
FACEBOOK     593
GOOGLE       320
MICROSOFT    464
Name: Sales, dtype: int64

In [ ]:
# Group by summary
df.groupby("Company").describe()

# describe all about sales

          Sales
          count   mean         std    min     25%    50%     75%    max
Company
FACEBOOK    2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOGLE      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MICROSOFT   2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

Aggregate Function

In [51]:
# calculate means for overall sales column 
df["Sales"].mean()

np.float64(229.5)

In [52]:
# calculate the Standard derviation for overall sales column 
df["Sales"].std()

100.89945490437498

In [56]:
# calculate the percentile for overall sales column
df["Sales"].quantile(0.9)

np.float64(345.0)

Merging DataFrames

In [65]:
df1 = pd.DataFrame(
    {
        "A":["A0","A1","A2","A3"],
        "B":["B0","B1","B2","B3"],
        "C":["C0","C1","C2","C3"],
        "D":["D0","D1","D2","D3"]
    },
    index=[0,1,2,3]
)
df2 = pd.DataFrame(
    {
        "A":["A4","A5","A6","A7"],
        "B":["B4","B5","B6","B7"],
        "C":["C4","C5","C6","C7"],
        "D":["D4","D5","D6","D7"]
    },
    index = [4,5,6,7]
)
df3 = pd.DataFrame(
    {
        "A":["A8","A9","A10","A11"],
        "B":["B8","B9","B10","B11"],
        "C":["C8","C9","C10","C11"],
        "D":["D8","D9","D10","D11"]
    },
    index = [8,9,10,11]
)

print(df1)
print(df2)
print(df3)

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
    A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7
      A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

Concatination With axis = 0

In [67]:
df_concat=pd.concat([df1,df2,df3])
df_concat

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

Concatination with axis =1

In [68]:
df_concat=pd.concat([df1,df2,df3], axis =1)
df_concat

      A    B    C    D    A    B    C    D    A    B    C    D
0    A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN   A5   B5   C5   D5  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN   A6   B6   C6   D6  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN   A7   B7   C7   D7  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A8   B8   C8   D8
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A9   B9   C9   D9
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A10  B10  C10  D10
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11

In [69]:
# Change NaN value with some default values
df_concat.fillna("-")

     A   B   C   D   A   B   C   D    A    B    C    D
0   A0  B0  C0  D0   -   -   -   -    -    -    -    -
1   A1  B1  C1  D1   -   -   -   -    -    -    -    -
2   A2  B2  C2  D2   -   -   -   -    -    -    -    -
3   A3  B3  C3  D3   -   -   -   -    -    -    -    -
4    -   -   -   -  A4  B4  C4  D4    -    -    -    -
5    -   -   -   -  A5  B5  C5  D5    -    -    -    -
6    -   -   -   -  A6  B6  C6  D6    -    -    -    -
7    -   -   -   -  A7  B7  C7  D7    -    -    -    -
8    -   -   -   -   -   -   -   -   A8   B8   C8   D8
9    -   -   -   -   -   -   -   -   A9   B9   C9   D9
10   -   -   -   -   -   -   -   -  A10  B10  C10  D10
11   -   -   -   -   -   -   -   -  A11  B11  C11  D11

Merging by Single common key

In [71]:
# Syntax
# df_concat=pd.merge(
#     df1,df2,df3,
#     how = "inner",
#     on = None,
#     left_on =None,
#     Right_on = None,
#     Left_index = None,
#     Right_index = None
# )

In [74]:
pd.merge(
    df1,df2
)

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [77]:
left = pd.DataFrame({
    "key":["K0","K1","K2","K3"],
    "A":["A0","A1","A2","A3"],
    "B":["B0","B1","B2","B3"]
})
right = pd.DataFrame({
    "key":["K0","K1","K2","K3"],
    "C":["C0","C1","C2","C3"],
    "D":["D0","D1","D2","D3"]
})

print(left)
print(right)

  key   A   B
0  K0  A0  B0
1  K1  A1  B1
2  K2  A2  B2
3  K3  A3  B3
  key   C   D
0  K0  C0  D0
1  K1  C1  D1
2  K2  C2  D2
3  K3  C3  D3

In [79]:
df_all=pd.merge(left,right)
df_all

  key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

In [ ]:
df_inner=pd.merge(left,right,
                  on = "key")
df_inner # default merge is an inner merge

  key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

In [84]:
df_out=pd.merge(left,right,how= "outer")
df_out

  key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

Merging by 2 common key

In [85]:
left = pd.DataFrame({
    "key1":["K0","K0","K1","K2"],
    "key2":["K0","K1","K0","K1"],
    "A":["A0","A1","A2","A3"],
    "B":["B0","B1","B2","B3"]
})
right = pd.DataFrame({
    "key1":["K0","K1","K2","K3"],
    "key2":["K0","K0","K0","K0"],
    "C":["C0","C1","C2","C3"],
    "D":["D0","D1","D2","D3"]
})

print(left)
print(right)

  key1 key2   A   B
0   K0   K0  A0  B0
1   K0   K1  A1  B1
2   K1   K0  A2  B2
3   K2   K1  A3  B3
  key1 key2   C   D
0   K0   K0  C0  D0
1   K1   K0  C1  D1
2   K2   K0  C2  D2
3   K3   K0  C3  D3

In [ ]:
df_inner1=pd.merge(left,right,
                  on = ["key1","key2"])
df_inner1

  key1 key2   A   B   C   D
0   K0   K0  A0  B0  C0  D0
1   K1   K0  A2  B2  C1  D1

Left Merge

In [89]:
df_left = pd.merge(left,right,on = ["key1","key2"],how="left")
df_left

  key1 key2   A   B    C    D
0   K0   K0  A0  B0   C0   D0
1   K0   K1  A1  B1  NaN  NaN
2   K1   K0  A2  B2   C1   D1
3   K2   K1  A3  B3  NaN  NaN

In [ ]:
# If left kai eqivalend right ki value hai with respective to key1 , key2 then show hoga werna NaN

Right Merge

In [90]:
df_right = pd.merge(left,right,on = ["key1","key2"],how="right")
df_right

  key1 key2    A    B   C   D
0   K0   K0   A0   B0  C0  D0
1   K1   K0   A2   B2  C1  D1
2   K2   K0  NaN  NaN  C2  D2
3   K3   K0  NaN  NaN  C3  D3

In [ ]:
# Same as left ager irght sai eqivalent hai tho show verna NaN

Outer Merge

In [91]:
df_out = pd.merge(left,right,on = ["key1","key2"],how="outer")
df_out

  key1 key2    A    B    C    D
0   K0   K0   A0   B0   C0   D0
1   K0   K1   A1   B1  NaN  NaN
2   K1   K0   A2   B2   C1   D1
3   K2   K0  NaN  NaN   C2   D2
4   K2   K1   A3   B3  NaN  NaN
5   K3   K0  NaN  NaN   C3   D3

In [ ]:
# Sub ko include karega koi key ka same ka seen nhi hai

In [92]:
print(df1)
print(df2)

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
    A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [ ]:
df_in = pd.merge(df1 ,df2)
df_in
# here by defsult key is A,B,C,D tho koi bhi value match nhi ho rha hai isliye kuch nhi aya

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [ ]:
# kuch common hi nhi hai isliye kuch show hi nhi hua

In [96]:
df_outer = pd.merge(df1,df2,how="outer" )
# row wise
df_outer

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [ ]:
#Sub ko include kar liye
# By default hum nai kuch key nhi diya tho wo lai lai ga do dono table mai common ho example A,B,C,D

Joins in panda DataFrame

In [ ]:
# most index based join

In [98]:
import pandas as pd
left = pd.DataFrame({
    "A":["A0","A1","A2"],
    "B":["B0","B1","B2"]
},index = ["K0","K1","K2"]
                    )

right = pd.DataFrame({
    "C":["C0","C1","C2"],
    "D":["D0","D1","D2"]
},index = ["K0","K2","K3"]
                    )

print(left)
print(right)

     A   B
K0  A0  B0
K1  A1  B1
K2  A2  B2
     C   D
K0  C0  D0
K2  C1  D1
K3  C2  D2

In [ ]:
left.join(right)  # Respective to left 
# similar to left outter join

     A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C1   D1

In [ ]:
left.join(right , how  ="outer")
# jo match ho rako werna jane doooooo

      A    B    C    D
K0   A0   B0   C0   D0
K1   A1   B1  NaN  NaN
K2   A2   B2   C1   D1
K3  NaN  NaN   C2   D2

In [ ]:
# similar to right outter join
right.join(left)

     C   D    A    B
K0  C0  D0   A0   B0
K2  C1  D1   A2   B2
K3  C2  D2  NaN  NaN