Miscellaneous Operations on DataFrame

In [3]:
import numpy as np
import pandas as pd

df.apply() Method

In [4]:
# Create demo DataFrame with real-looking model names and metrics

data = {
    "model_name": [
        "Logistic Regression",
        "Decision Tree",
        "Random Forest",
        "XGBoost",
        "LightGBM",
        "KNN",
        "Naive Bayes",
        "SVM",
        "CNN",
        "LSTM"
    ],

    "execution_time": [0.5, 0.8, 2.3, 3.1, 2.8, 1.2, 0.6, 1.9, 4.5, 5.0],  # seconds

    "model_size": [2.3, 5.6, 45.2, 60.1, 55.8, 8.4, 1.2, 12.3, 120.5, 150.7],  # MB

    "accuracy": [0.82, 0.78, 0.89, 0.91, 0.90, 0.76, 0.74, 0.88, 0.93, 0.92],

    "f1_score": [0.80, 0.75, 0.87, 0.90, 0.89, 0.74, 0.72, 0.86, 0.92, 0.91],

    "precision": [0.81, 0.76, 0.88, 0.91, 0.90, 0.75, 0.73, 0.87, 0.93, 0.92],

    "recall": [0.79, 0.74, 0.86, 0.89, 0.88, 0.73, 0.71, 0.85, 0.91, 0.90]
}

In [5]:
df = pd.DataFrame(data)
df

,model_name,execution_time,model_size,accuracy,f1_score,precision,recall
0,Logistic Regression,0.5,2.3,0.82,0.80,0.81,0.79
1,Decision Tree,0.8,5.6,0.78,0.75,0.76,0.74
2,Random Forest,2.3,45.2,0.89,0.87,0.88,0.86
3,XGBoost,3.1,60.1,0.91,0.90,0.91,0.89
4,LightGBM,2.8,55.8,0.90,0.89,0.90,0.88
5,KNN,1.2,8.4,0.76,0.74,0.75,0.73
6,Naive Bayes,0.6,1.2,0.74,0.72,0.73,0.71
7,SVM,1.9,12.3,0.88,0.86,0.87,0.85
8,CNN,4.5,120.5,0.93,0.92,0.93,0.91
9,LSTM,5.0,150.7,0.92,0.91,0.92,0.90

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   model_name      10 non-null     object
 1   execution_time  10 non-null     float64
 2   model_size      10 non-null     float64
 3   accuracy        10 non-null     float64
 4   f1_score        10 non-null     float64
 5   precision       10 non-null     float64
 6   recall          10 non-null     float64
dtypes: float64(6), object(1)
memory usage: 692.0+ bytes

Apply user defined Functions

In [7]:
# Define function which converts execution time from second to milli_seconds
def testfunc(x):
    model_name = "_".join(x.split())
    model_name = model_name.lower()
    return model_name

In [8]:
#convert model name to lower case and space by undersocre
df["model_name"].apply(testfunc)

0    logistic_regression
1          decision_tree
2          random_forest
3                xgboost
4               lightgbm
5                    knn
6            naive_bayes
7                    svm
8                    cnn
9                   lstm
Name: model_name, dtype: object

In [9]:
df

,model_name,execution_time,model_size,accuracy,f1_score,precision,recall
0,Logistic Regression,0.5,2.3,0.82,0.80,0.81,0.79
1,Decision Tree,0.8,5.6,0.78,0.75,0.76,0.74
2,Random Forest,2.3,45.2,0.89,0.87,0.88,0.86
3,XGBoost,3.1,60.1,0.91,0.90,0.91,0.89
4,LightGBM,2.8,55.8,0.90,0.89,0.90,0.88
5,KNN,1.2,8.4,0.76,0.74,0.75,0.73
6,Naive Bayes,0.6,1.2,0.74,0.72,0.73,0.71
7,SVM,1.9,12.3,0.88,0.86,0.87,0.85
8,CNN,4.5,120.5,0.93,0.92,0.93,0.91
9,LSTM,5.0,150.7,0.92,0.91,0.92,0.90

In [10]:
# using map() instead of apply
df["model_name"].map(testfunc)

0    logistic_regression
1          decision_tree
2          random_forest
3                xgboost
4               lightgbm
5                    knn
6            naive_bayes
7                    svm
8                    cnn
9                   lstm
Name: model_name, dtype: object

In [11]:
df

,model_name,execution_time,model_size,accuracy,f1_score,precision,recall
0,Logistic Regression,0.5,2.3,0.82,0.80,0.81,0.79
1,Decision Tree,0.8,5.6,0.78,0.75,0.76,0.74
2,Random Forest,2.3,45.2,0.89,0.87,0.88,0.86
3,XGBoost,3.1,60.1,0.91,0.90,0.91,0.89
4,LightGBM,2.8,55.8,0.90,0.89,0.90,0.88
5,KNN,1.2,8.4,0.76,0.74,0.75,0.73
6,Naive Bayes,0.6,1.2,0.74,0.72,0.73,0.71
7,SVM,1.9,12.3,0.88,0.86,0.87,0.85
8,CNN,4.5,120.5,0.93,0.92,0.93,0.91
9,LSTM,5.0,150.7,0.92,0.91,0.92,0.90

In [12]:
# convert execution time from second to milli_second - using apply
df["execution_time"].apply(lambda x : x*1000)

0     500.0
1     800.0
2    2300.0
3    3100.0
4    2800.0
5    1200.0
6     600.0
7    1900.0
8    4500.0
9    5000.0
Name: execution_time, dtype: float64

In [13]:
def change_time(x):
    return x*1000

In [14]:
# COnvert execution time from second to milli-second - using map
df["execution_time"].map(change_time)

0     500.0
1     800.0
2    2300.0
3    3100.0
4    2800.0
5    1200.0
6     600.0
7    1900.0
8    4500.0
9    5000.0
Name: execution_time, dtype: float64

In [15]:
df

,model_name,execution_time,model_size,accuracy,f1_score,precision,recall
0,Logistic Regression,0.5,2.3,0.82,0.80,0.81,0.79
1,Decision Tree,0.8,5.6,0.78,0.75,0.76,0.74
2,Random Forest,2.3,45.2,0.89,0.87,0.88,0.86
3,XGBoost,3.1,60.1,0.91,0.90,0.91,0.89
4,LightGBM,2.8,55.8,0.90,0.89,0.90,0.88
5,KNN,1.2,8.4,0.76,0.74,0.75,0.73
6,Naive Bayes,0.6,1.2,0.74,0.72,0.73,0.71
7,SVM,1.9,12.3,0.88,0.86,0.87,0.85
8,CNN,4.5,120.5,0.93,0.92,0.93,0.91
9,LSTM,5.0,150.7,0.92,0.91,0.92,0.90

In [17]:
# model_score = 0.8"f1_score +0.1*(1/execution_time)+ 0.1*(1/model_size)
df["model_score"]= (
    0.8*df["f1_score"]+
    0.1*(1/df["execution_time"])+
    0.1*(1/df["model_size"])
    
)

In [18]:
df

,model_name,execution_time,model_size,accuracy,f1_score,precision,recall,model_score
0,Logistic Regression,0.5,2.3,0.82,0.80,0.81,0.79,0.883478
1,Decision Tree,0.8,5.6,0.78,0.75,0.76,0.74,0.742857
2,Random Forest,2.3,45.2,0.89,0.87,0.88,0.86,0.741691
3,XGBoost,3.1,60.1,0.91,0.90,0.91,0.89,0.753922
4,LightGBM,2.8,55.8,0.90,0.89,0.90,0.88,0.749506
5,KNN,1.2,8.4,0.76,0.74,0.75,0.73,0.687238
6,Naive Bayes,0.6,1.2,0.74,0.72,0.73,0.71,0.826000
7,SVM,1.9,12.3,0.88,0.86,0.87,0.85,0.748762
8,CNN,4.5,120.5,0.93,0.92,0.93,0.91,0.759052
9,LSTM,5.0,150.7,0.92,0.91,0.92,0.90,0.748664

In [ ]:
# Even through Random Forest model have high f1 score than decision tree , the overall score for Random Forest is less than Decison Tres

Apply built in function

In [22]:
#calclutate lenght  of model name strings
df["len_model_name"]=df["model_name"].apply(len)

In [23]:
df

,model_name,execution_time,model_size,accuracy,f1_score,precision,recall,model_score,len_model_name
0,Logistic Regression,0.5,2.3,0.82,0.80,0.81,0.79,0.883478,19
1,Decision Tree,0.8,5.6,0.78,0.75,0.76,0.74,0.742857,13
2,Random Forest,2.3,45.2,0.89,0.87,0.88,0.86,0.741691,13
3,XGBoost,3.1,60.1,0.91,0.90,0.91,0.89,0.753922,7
4,LightGBM,2.8,55.8,0.90,0.89,0.90,0.88,0.749506,8
5,KNN,1.2,8.4,0.76,0.74,0.75,0.73,0.687238,3
6,Naive Bayes,0.6,1.2,0.74,0.72,0.73,0.71,0.826000,11
7,SVM,1.9,12.3,0.88,0.86,0.87,0.85,0.748762,3
8,CNN,4.5,120.5,0.93,0.92,0.93,0.91,0.759052,3
9,LSTM,5.0,150.7,0.92,0.91,0.92,0.90,0.748664,4

In [ ]:
# calculate sqrt of precission
df["precision"].apply(np.sqrt)

0    0.900000
1    0.871780
2    0.938083
3    0.953939
4    0.948683
5    0.866025
6    0.854400
7    0.932738
8    0.964365
9    0.959166
Name: precision, dtype: float64

In [25]:
# sort value based on score
df.sort_values(by="model_score" , ascending=False)

,model_name,execution_time,model_size,accuracy,f1_score,precision,recall,model_score,len_model_name
0,Logistic Regression,0.5,2.3,0.82,0.80,0.81,0.79,0.883478,19
6,Naive Bayes,0.6,1.2,0.74,0.72,0.73,0.71,0.826000,11
8,CNN,4.5,120.5,0.93,0.92,0.93,0.91,0.759052,3
3,XGBoost,3.1,60.1,0.91,0.90,0.91,0.89,0.753922,7
4,LightGBM,2.8,55.8,0.90,0.89,0.90,0.88,0.749506,8
7,SVM,1.9,12.3,0.88,0.86,0.87,0.85,0.748762,3
9,LSTM,5.0,150.7,0.92,0.91,0.92,0.90,0.748664,4
1,Decision Tree,0.8,5.6,0.78,0.75,0.76,0.74,0.742857,13
2,Random Forest,2.3,45.2,0.89,0.87,0.88,0.86,0.741691,13
5,KNN,1.2,8.4,0.76,0.74,0.75,0.73,0.687238,3

Date & Time

pandas.Timestamp()

In [26]:
# construct a TimeStamp frim a string date
pd.Timestamp("2025-08-18 14:30:15")

Timestamp('2025-08-18 14:30:15')

In [27]:
pd.Timestamp("2025-08-18")

Timestamp('2025-08-18 00:00:00')

In [28]:
pd.Timestamp("08-18-2025")

Timestamp('2025-08-18 00:00:00')

In [ ]:
# print the time stamp

pandas.to_datetime()

In [30]:
# single srings

pd.to_datetime("2025-08-18")

Timestamp('2025-08-18 00:00:00')

In [31]:
# list of strings
pd.to_datetime(["2025-08-18" ,"2025-08-19"])

DatetimeIndex(['2025-08-18', '2025-08-19'], dtype='datetime64[ns]', freq=None)

In [37]:
# list of strings
pd.to_datetime(["2025-08-18" ,"2025-08-19"])[0]

Timestamp('2025-08-18 00:00:00')

In [36]:
# Integers each values ( nanoseconds seconds since 1970)
pd.to_datetime([1659393533 , 1789752303] , unit ="s")

DatetimeIndex(['2022-08-01 22:38:53', '2026-09-18 17:25:03'], dtype='datetime64[ns]', freq=None)

pd.date_range()

In [39]:
# create a 5 date string for ts 1
ts1 = pd.Timestamp("2025-08-18 14:40:44")
ts1

Timestamp('2025-08-18 14:40:44')

In [41]:
pd.date_range(ts1 , periods = 5)

DatetimeIndex(['2025-08-18 14:40:44', '2025-08-19 14:40:44',
               '2025-08-20 14:40:44', '2025-08-21 14:40:44',
               '2025-08-22 14:40:44'],
              dtype='datetime64[ns]', freq='D')

In [49]:
start = pd.Timestamp("2026-9-07")
end = pd.Timestamp("2026-9-09")
pd.date_range(start,end)

DatetimeIndex(['2026-09-07', '2026-09-08', '2026-09-09'], dtype='datetime64[ns]', freq='D')

pd.Timedelta()

In [50]:
# adding an integer to timestamp
start = pd.Timestamp(2025 ,1,1)

In [51]:
pd.Timedelta(days = 2 , hours =4)

Timedelta('2 days 04:00:00')

In [ ]:
start = pd.Timestamp(2025 ,1,1)  + pd.Timedelta(days = 2 , hours =4)

start
# date or time are added

Timestamp('2025-01-03 04:00:00')

Creating a DataFrame with date columns

In [55]:
data = {
    "date":["2025-8-18","2025-8-19","2025-8-20"],
    "value":[10,20,30]
}

df = pd.DataFrame(data)
df

        date  value
0  2025-8-18     10
1  2025-8-19     20
2  2025-8-20     30

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    3 non-null      object
 1   value   3 non-null      int64
dtypes: int64(1), object(1)
memory usage: 180.0+ bytes

In [64]:
# covert data in to datetime astype instead of object
df["date"] = pd.to_datetime(df["date"])
print(df)

        date  value
0 2025-08-18     10
1 2025-08-19     20
2 2025-08-20     30

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    3 non-null      datetime64[ns]
 1   value   3 non-null      int64
dtypes: datetime64[ns](1), int64(1)
memory usage: 180.0 bytes

Pandas datetime = Numpy datetime64 + Timestamp wrapper + extra time_serues_feature

operations on Time & Date

In [66]:
s = pd.Series(pd.date_range("2025-1-1" , periods=3 , freq = "D"))
td  = pd.Series( [ pd.Timedelta(hours=i) for i in range(3)])

In [67]:
print(s)
print(td)

0   2025-01-01
1   2025-01-02
2   2025-01-03
dtype: datetime64[ns]
0   0 days 00:00:00
1   0 days 01:00:00
2   0 days 02:00:00
dtype: timedelta64[ns]

In [70]:
df  = pd.DataFrame(dict(A=s , B = td))
df

           A               B
0 2025-01-01 0 days 00:00:00
1 2025-01-02 0 days 01:00:00
2 2025-01-03 0 days 02:00:00

In [ ]:
# add timedelta to a timeseries
df["C"]=s + td

In [72]:
df

           A               B                   C
0 2025-01-01 0 days 00:00:00 2025-01-01 00:00:00
1 2025-01-02 0 days 01:00:00 2025-01-02 01:00:00
2 2025-01-03 0 days 02:00:00 2025-01-03 02:00:00

Filter operation on date_time Columns

In [76]:
# sample data
data = {
    "Event":["A","B","C","D","E"],
    "Date":pd.to_datetime(["2025-08-18", "2025-08-19","2025-08-20","2025-08-21","2025-08-22"])
}
data

df = pd.DataFrame(data)
df

  Event       Date
0     A 2025-08-18
1     B 2025-08-19
2     C 2025-08-20
3     D 2025-08-21
4     E 2025-08-22

In [77]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Event   5 non-null      object
 1   Date    5 non-null      datetime64[ns]
dtypes: datetime64[ns](1), object(1)
memory usage: 212.0+ bytes

In [78]:
#filter by specfic data
df["Date"]=="2025-08-20"

0    False
1    False
2     True
3    False
4    False
Name: Date, dtype: bool

In [79]:
df[df["Date"]=="2025-08-20"]

  Event       Date
2     C 2025-08-20

In [80]:
# filter by range
df[(df["Date"]>="2025-08-18") & (df["Date"]<="2025-08-22")]

  Event       Date
0     A 2025-08-18
1     B 2025-08-19
2     C 2025-08-20
3     D 2025-08-21
4     E 2025-08-22

In [82]:
df["Date"].dt

In [81]:
# filter by day of week
df[df["Date"].dt.dayofweek==2]

  Event       Date
2     C 2025-08-20

Benefits of DateTimeIndex over regular columns

In [83]:
#sample data
data = {
    "Date":pd.date_range("2025-08-18", periods=5 , freq="D"),
    "Value":[10,20,30,40,50]

}
df_col=pd.DataFrame(data)
#DataFrame with DateTimeIndex
df_index= df_col.drop( columns="Date")
df_index.index = data["Date"]

print("DataFrame with datetime columns :\n", df_col)
print("\nDataFrame with DatetimeIndex:\n", df_index)

DataFrame with datetime columns :
         Date  Value
0 2025-08-18     10
1 2025-08-19     20
2 2025-08-20     30
3 2025-08-21     40
4 2025-08-22     50

DataFrame with DatetimeIndex:
             Value
2025-08-18     10
2025-08-19     20
2025-08-20     30
2025-08-21     40
2025-08-22     50

In [ ]:
# flitering a specfic data
# using date time column
print(df_col[df_col["Date"] == "2025-8-20"])

        Date  Value
2 2025-08-20     30

In [87]:
#using DatetimIndex
df_index.loc["2025-8-20"]

Value    30
Name: 2025-08-20 00:00:00, dtype: int64

In [89]:
# slicing by date range 
# using datetime columns
df_col[(df_col["Date"] >= "2025-08-19") & (df_col["Date"]<= "2025-08-21")]

        Date  Value
1 2025-08-19     20
2 2025-08-20     30
3 2025-08-21     40

In [91]:
# using datetimeIndex
df_index["2025-08-19":"2025-08-21"]

            Value
2025-08-19     20
2025-08-20     30
2025-08-21     40