In [1]:
import numpy as np
import pandas as pd

Multiindexing & Pivot Talbes in pandas

In [5]:
arrays = [
    ["North" , "North" , "South" , "South"],
    [2024 , 2025 , 2024 , 2025]
]

In [6]:
# Create multi index
index = pd.MultiIndex.from_arrays( arrays , names=("Region" ,"Year"))
index

MultiIndex([('North', 2024),
            ('North', 2025),
            ('South', 2024),
            ('South', 2025)],
           names=['Region', 'Year'])

In [7]:
type(index)

pandas.core.indexes.multi.MultiIndex

In [9]:
# cretaing DataFrame
df  = pd.DataFrame(
    np.random.randint(100,500, size = (4,2)),
    index= index,
    columns = ["Product A" , "Product B"]
)
df

             Product A  Product B
Region Year
North  2024        427        438
       2025        154        105
South  2024        472        263
       2025        195        304

In [14]:
# print dataframe
df

             Product A  Product B
Region Year
North  2024        427        438
       2025        154        105
South  2024        472        263
       2025        195        304

In [15]:
df.index

MultiIndex([('North', 2024),
            ('North', 2025),
            ('South', 2024),
            ('South', 2025)],
           names=['Region', 'Year'])

In [16]:
df.columns

Index(['Product A', 'Product B'], dtype='object')

In [23]:
# Slicing region
print(df.loc["North"])
print("--"*50)
print(df.loc["North" , 2024])
print("--"*50)
print(df.loc["North", 2025])

      Product A  Product B
Year
2024        427        438
2025        154        105
----------------------------------------------------------------------------------------------------
Product A    427
Product B    438
Name: (North, 2024), dtype: int32
----------------------------------------------------------------------------------------------------
Product A    154
Product B    105
Name: (North, 2025), dtype: int32

In [24]:
# Slicing region
print(df.loc["South"])
print("--"*50)
print(df.loc["South" , 2024])
print("--"*50)
print(df.loc["South", 2025])

      Product A  Product B
Year
2024        472        263
2025        195        304
----------------------------------------------------------------------------------------------------
Product A    472
Product B    263
Name: (South, 2024), dtype: int32
----------------------------------------------------------------------------------------------------
Product A    195
Product B    304
Name: (South, 2025), dtype: int32

In [32]:
df.xs("North" , level = "Region")  # another method for slicing in multidimensional

      Product A  Product B
Year
2024        427        438
2025        154        105

In [31]:
#All region year 2024
print(df.loc[pd.IndexSlice[:,2024,:]])

        Product A  Product B
Region
North         427        438
South         472        263

In [33]:
df.xs(2024 , level="Year")

        Product A  Product B
Region
North         427        438
South         472        263

In [ ]:
# Slice Prodouct
df.xs("Product A" , axis = 1)
# df.loc[: , "Product A"]

Region  Year
North   2024    427
        2025    154
South   2024    472
        2025    195
Name: Product A, dtype: int32

In [41]:
df.xs("Product B", axis = 1)

Region  Year
North   2024    438
        2025    105
South   2024    263
        2025    304
Name: Product B, dtype: int32

In [44]:
# Acess Specfic Year of a region ex south 2025
print(df.loc[("South", 2025)])

Product A    195
Product B    304
Name: (South, 2025), dtype: int32

In [45]:
df.xs(("South", 2025))

Product A    195
Product B    304
Name: (South, 2025), dtype: int32

Aggregation using multiindex

In [46]:
df

             Product A  Product B
Region Year
North  2024        427        438
       2025        154        105
South  2024        472        263
       2025        195        304

In [48]:
df.index

MultiIndex([('North', 2024),
            ('North', 2025),
            ('South', 2024),
            ('South', 2025)],
           names=['Region', 'Year'])

In [49]:
# Sum of product per region
df.groupby(level = "Region").sum()

        Product A  Product B
Region
North         581        543
South         667        567

In [53]:
# Average sales of product per region
df.groupby(level = "Region").mean()

        Product A  Product B
Region
North       290.5      271.5
South       333.5      283.5

In [54]:
# Sum of product per year
df.groupby(level="Year").sum()

      Product A  Product B
Year
2024        899        701
2025        349        409

Resetting the Multindex

In [55]:
df

             Product A  Product B
Region Year
North  2024        427        438
       2025        154        105
South  2024        472        263
       2025        195        304

In [57]:
df_reset=df.reset_index()
df_reset

  Region  Year  Product A  Product B
0  North  2024        427        438
1  North  2025        154        105
2  South  2024        472        263
3  South  2025        195        304

Pivot Table

In [59]:
data = {
    "Region":["North","North","South","South"],
    "Year":[2024,2025,2024,2025],
    "Product":["PA","PB","PA","PB"],
    "Sales":[232 , 192 , 412 , 156]
}

In [62]:
df=pd.DataFrame(data)
df

  Region  Year Product  Sales
0  North  2024      PA    232
1  North  2025      PB    192
2  South  2024      PA    412
3  South  2025      PB    156

In [63]:
# Create a Pivot table : total sales per Region per Prodouct
pivot = pd.pivot_table( 
                       df,
                       values ="Sales",
                       index = "Region",
                       columns = "Product",
                       aggfunc = "sum")
pivot

Product   PA   PB
Region
North    232  192
South    412  156

Cross - tabulation

default output : counts/Frequencies

In [64]:
data = {
    "Gender":["Male","Male","Female","Female","Male","Female","Male","Female"],
    "Preference":["Tea","Coffee","Coffee","Tea","Tea","Coffee","Coffee","Tea"]
}

In [65]:
df = pd.DataFrame(data)
df

   Gender Preference
0    Male        Tea
1    Male     Coffee
2  Female     Coffee
3  Female        Tea
4    Male        Tea
5  Female     Coffee
6    Male     Coffee
7  Female        Tea

In [66]:
# Create Cross Table using pivot table
pivot = df.pivot_table(
    df,
    index  = "Gender",
    columns = "Preference",
    aggfunc = "size"
    
)
pivot

Preference  Coffee  Tea
Gender
Female           2    2
Male             2    2

In [67]:
# Create Crosstab
pd.crosstab(df["Gender"], df["Preference"])

Preference  Coffee  Tea
Gender
Female           2    2
Male             2    2